as yet unclassified
seed

	self instance 
			add: (DrinklistDrink create: 'Cola' whichCosts: 1 initialStock: 10 minimumStock: 2);
			add: (DrinklistDrink create: 'Bier' whichCosts: 1 initialStock: 10 minimumStock: 2);
			add: (DrinklistDrink create: 'Spritz' whichCosts: 1 initialStock: 10 minimumStock: 2);
			add: (DrinklistDrink create: 'Bauer' whichCosts: 2 initialStock: 10 minimumStock: 2);
			add: (DrinklistDrink create: 'Biobrause' whichCosts: 1 initialStock: 10 minimumStock: 2);
			add: (DrinklistUser create: 'test')